### ISSUE TITLE
Xml blank document error 

### ISSUE THREAD

**Issue by matty2123** [Royal-Modding/FS19_CameraSuspension#3]
Hello I’m using your mod I like it trouble is I’m getting a xml blank document error i narrowed it down by excluding mods and found it was this spitting the error out

**Comment by TyKonKet** [comment]
Probably it's an issue related to a mod vehicle made wrongly by the author, can you please provide me with the full text of the error?

**Comment by jason0611** [comment]
Just a guess: Maybe the royalSettings.xml in the modSettings folder is broken?

**Comment by matty2123** [comment]
Mod is working.
